config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :sessions, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :show]

  resources :reservations


  resources :restaurants do
    resources :reservations
  end


end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
  validates :party_size, numericality: [only_integer: true]
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reservations
  has_many :users, through: :reservations
  validates :name, :phone, :address, :description, :capacity, presence: :true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :reservations
  has_many :restaurants, through: :reservations
  validates :first_name, :last_name, :email, :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in."
    end
  end

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout "home"
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
before_filter :get_reservation, only: [:show, :edit, :update, :destroy]
before_filter :get_restaurant
# before_filter :authenticate_owns_reservations

  def index
    @reservations = current_user.reservations # => so only the current_user can see their own reservations
  end

  def show
   @reservations = Reservation.where(user_id: current_user.id)
  end

  def edit
  end

  def new
    @reservation = Reservation.new
  end

  def create
    # @reservation = @restaurant.reservations.build(reservation_params)
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id
    @reservation.restaurant_id = @restaurant.id

    seats_reserved = @restaurant.reservations.where("date > ? and date < ?", @reservation.date.beginning_of_hour, @reservation.date.beginning_of_hour + 1.hour).map(&:party_size).sum

    # seats_reserved = @restaurant.reservations
    #                                   .where("date > :start_time AND date < :end_time", {
    #                                     start_time: @reservation.date,
    #                                     end_time: @reservation.date + 1.hours
    #                                   }).map(&:party_size).sum


    seats_available = @restaurant.capacity - seats_reserved

    if @reservation.party_size >= seats_available
      flash[:alert] = "This reservation cannot be made."
      render :new
    else
      @reservation.save
      flash[:notice] = "Your reservation has been created."
      redirect_to restaurants_path
    end
  end

  def update

    if @reservation.update_attributes(reservation_params)
      redirect_to restaurant_reservation_path(@restaurant, @reservation)
    else
      render :new
    end
  end

  def destroy
    @reservation.destroy
      redirect_to restaurant_reservation_path(@restaurant, @reservation)
  end

  private

  # def authenticate_owns_reservations
  #   unless current_user.id == @reservation.user_id
  #     flash[:alert] = "You do not have access to this reservation."
  #     redirect_to '/'
  #   end
  # end

  def reservation_params
    params.require(:reservation).permit(:party_size, :date)
  end

  def get_reservation
    @reservation = Reservation.find(params[:id])
  end

  def get_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create


    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update_attributes(restaurant_params)
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
      redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :phone, :address, :description, :capacity)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_path, notice: "Logged in!"
    else
      flash.now[:alert] = "Please check your login information and try again."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to restaurants_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users, notice: "Sign up successful!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :phone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself</title>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
  <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="main">

<!-- Navbar -->

<nav class="navbar navbar-inverse" id="navigation-main">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="nav-title" href="/restaurants">Seat Yourself</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/restaurants">Home<span class="sr-only">(current)</span></a></li>


      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Restaurants<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/restaurants">Restaurants Near You</a></li>
            <li><a href="/restaurants/new">Add your restaurant</a></li>
          </ul>
      </li>

   <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Login<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/sessions/new">Login</a></li>
            <li><a href="/users/new">Register</a></li>
          </ul>
      </li>

      <li><a href="/reservations/show">My Reservations</a></li>
      <!-- Searchbar? -->
<!--
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- Body -->
  <div class="container" id="login-status-bar">
    <% if current_user %>
      <h5> Signed in as <%= current_user.first_name %> <%= link_to "[Log out]", session_path("current"), :method => :delete %></h4>
        <% else %>
      <%= %>
    <% end %>
  </div>



 <div class="container" id="flash_class">
    <div class="panel-body">
    <% if flash[:notice] %>
      <h5 id="notice" class="alert alert-success"><%= flash[:notice] %></h5>
    <% end %>
    <% if flash[:alert] %>
      <h5 id="alert" class="alert alert-danger"><%= flash[:alert] %></h5>
    <% end %>
    </div>
  </div>


<%= yield %>


<!-- Fixed Footer -->
<div class="footer">
  <h6 id="footer-color">Seat Yourself 2015</h6>
</div>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself</title>
  <%= stylesheet_link_tag    'home', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="body">



  <div class="container" id="landing">
    <div class="container">

        <div class="row">
            <div class="col-md-12 text-info title"><h1 class="welcome">Welcome to Seat Yourself</h1></div>
        </div>

        <div class="row">

          <a href="sessions/new">
            <div class="col-md-4"></div>
              <div class="col-md-2 btn btn-info" id="button-home1">
                <h4>
                  <span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span>
                    Login
                </h4>
            </div>
          </a>

           <a href="users/new">
             <div class="col-md-2 btn btn-info" id="button-home2">
                <h4>
                  Signup
                  <span class="glyphicon glyphicon-triangle-left" aria-hidden="true"></span>
                </h4>
            </div>
          </a>

          <div class="col-md-4"></div>

        </div>
    </div>


  </div>




</body>
</html>

app/views/pages/home.html.erb
<%= link_to 'Sign Up', new_user_path %>
<%= link_to 'Log In', new_session_path %>

app/views/reservations/index.html.erb
<div class="container con-background">
  <%= link_to "Back to Restaurants", restaurants_url %>

<%= @reservations each do |f| %>
  <h3 class="secondary-color">Party Size: <%= f.@reservation.party_size %></h3>
  <h3 class="secondary-color">Reservation Time: <%= f.@reservation.date %></h3>
<% end %>
</div>

app/views/reservations/new.html.erb
<div class="container con-background">
<h1 class="header-color">Make a Reservation</h1>

  <%= form_for [@restaurant, @reservation] do |f| %>

    <% if @reservation.errors.any? %>
      <h4 class="error-text"><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h4>
      <ul>
        <% @reservation.errors.full_messages.each do |msg| %>
          <li class="secondary-error-text"><%= msg %></li>
        <% end %>
      </ul>

    <% end %>

      <p>
        <%= f.label :party_size, class: "secondary-color" %><br>
        <%= f.text_field :party_size %>
      </p>

      <p>
        <%= f.label :date, class: "secondary-color" %><br>
        <%= f.datetime_select :date, discard_minute: true, discard_year: true %>
      </p>

      <p>
        <%= f.submit "Submit", class: "btn-info submit-button" %>
      </p>

  <% end %>
</div>

app/views/reservations/show.html.erb
<div class="container con-background">
  <%= link_to "Back to restaurants", restaurants_url %>

<%= @reservations each do |f| %>
  <h1 class="header-color"><%= f.@restaurant.name %></h1><hr>
  <h3 class="secondary-color">Party Size: <%= f.@reservation.party_size %></h3>
  <h3 class="secondary-color">Reservation Time: <%= f.@reservation.date %></h3>

</div>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>

  <% if @restaurant.errors.any? %>
    <h4 class="error-text"><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h4>
    <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li class="secondary-error-text"><%= msg %></li>
      <% end %>
    </ul>

  <% end %>

    <p>
      <%= f.label :name, class: "secondary-color" %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :phone, class: "secondary-color" %><br>
      <%= f.text_field :phone %>
    </p>

    <p>
      <%= f.label :address, class: "secondary-color" %><br>
      <%= f.text_field :address %>
    </p>

    <p>
      <%= f.label :description, class: "secondary-color" %><br>
      <%= f.text_field :description %>
    </p>

    <p>
      <%= f.label :capacity, class: "secondary-color" %><br>
      <%= f.text_field :capacity %>
    </p>

    <p>
      <%= f.submit "Submit", class: "btn-info submit-button" %>
    </p>

<% end %>

app/views/restaurants/edit.html.erb
<div class="container con-background">
    <h1 class="header-color">Update: "<%= @restaurant.name %>"</h1>
    <%= render "form" %>
</div>

app/views/restaurants/index.html.erb
<div class="container con-background">

    <h1 class="header-color">Restaurants</h1>
    <%= link_to 'Add a Restaurant', new_restaurant_path %>

    <div class="containter">
      <div class="row">
        <div class="col-xs-12 col-md-12">
           <div class="thumbnail">
              <% @restaurants.each do |restaurant| %>
                <a href="<%= restaurant_path(restaurant) %>"><h5><%= restaurant.name %></h5></a>
                  <h6>Address: <%= restaurant.address %></h6>
                <hr>
              <% end %>
          </div>
        </div>
      </div>
    </div>

</div>

app/views/restaurants/new.html.erb
<div class="container con-background">
<h1 class="header-color">Add a Restaurant</h1>

<%= render "form" %>
</div>

app/views/restaurants/show.html.erb
<div class="container con-background">
  <%= link_to "Back to restaurants", restaurants_url %> <% if current_user %> | <span class="label label-info"><%= link_to "Edit", edit_restaurant_path(@restaurant) %></span> | <span class="label label-info"><%= link_to "Delete", @restaurant, method: :delete, data: {confirm: "Are you sure?"} %><% end %></span>

  <h1 class="header-color"><%= @restaurant.name %></h1><hr>
  <h3 class="secondary-color"><%= @restaurant.phone %></h3>
  <h4 class="secondary-color"><%= @restaurant.address %></h4>
  <h5 class="secondary-color"><%= @restaurant.description %></h5>

  <h1 class="secondary-color"><%= link_to "Book a Reservation!", new_restaurant_reservation_path(@restaurant) %></h1>
</div>

app/views/users/new.html.erb
<div class="container con-background">

  <% if current_user %>
    <h5 class="header-color">You are already logged in. Please log out to sign up for a new account.</h5>

    <% else %>
    <h1 class="header-color">Please Sign Up</h1>
      <%= form_for @user do |f| %>

        <div class="errors">
          <% if @user.errors.any? %>
            <h4 >Please check the form for errors and try again.</h4>
              <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
              <% end %>
          <% end %>
        </div>

        <div class="field">
          <p>
            <%= f.label :first_name %><br/>
            <%= f.text_field :first_name %>
          </p>
        </div>

        <div class="field">
          <p>
            <%= f.label :last_name %><br/>
            <%= f.text_field :last_name %>
          </p>
        </div>

        <div class="field">
          <p>
            <%= f.label :email %><br/>
            <%= f.text_field :email %>
          </p>
        </div>

        <div class="field">
          <p>
            <%= f.label :password %><br/>
            <%= f.password_field :password %>
          </p>
        </div>

        <div class="field">
          <p>
            <%= f.label :password_confirmation %><br/>
            <%= f.password_field :password_confirmation %>
          </p>
        </div>

        <div class="field">
          <p>
            <%= f.label :phone %><br/>
            <%= f.text_field :phone %>
          </p>
        </div>

        <p><div class="submit"><%= f.submit %></div></p>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container con-background">
<h1 class="header-color">User Portal </h1>

<%= current_user.reservations.each do |f| %>
    <h3 class="secondary-color">Restaurant: <%= f.restaurant %></h3>
    <h3 class="secondary-color">Party Size: <%= f.party_size %></h3>
    <h3 class="secondary-color">Reservation Time: <%= f.date %></h3>
    <hr>
<% end %>
</div>